DEBUG           = 0       ; Enable code that only is included for debug builds
TIMING          = 0       ; Change border color to show drawing progress. Only supported on the C64

; --- Uncomment one of the following two lines to select the build target.
;     Alternatively, either symbol can be defined using the ca65/cl65 command line.

;C64             = 1      ; Set to 1 to build for C64. Either this or PET must be 1
;PET             = 1      ; Set to 1 to build for PET. Either this or C64 must be 1